W-10745942: FTP Proxy
mulesoft/mule-ftp-connector pull request #273
Opened 2022-04-05 13:41 UTC by francisco-nery

Don't merge

2022-04-05 20:01 UTC, nicomz requested changes

2022-05-03 02:22 UTC, acurci-at-mulesoft requested changes
@Fran, I have some concerns about the ports and names on the composer files regarding Jenkins executions. Did you have in mind the possibility to have two execution simultaneously? (for example, master and support branches in the scheduled executions)
What will the behavior be?

2022-05-09 17:02 UTC, acurci-at-mulesoft approved these changes

2022-05-27 20:05 UTC, nicomz requested changes

2022-05-27 20:05 UTC, nicomz commented on src/main/java/org/mule/extension/ftp/internal/proxy/MuleFTPHTTPClient.java
> +public class MuleFTPHTTPClient extends FTPHTTPClient {
jdoc

2022-05-27 20:05 UTC, nicomz commented on src/main/java/org/mule/extension/ftp/internal/proxy/MuleFTPHTTPClient.java
> +    if (proxy instanceof HttpsTunnelProxy) {
This should also be discussed. If you're checking here if this class is instance off looks like adding the TLSConetext to the API is not needed.

2022-05-30 19:22 UTC, nicomz approved these changes

2022-05-30 19:42 UTC, merged